apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking-space-service
  labels:
    name: coworking-space
spec:
  selector:
    matchLabels:
      name: coworking-space
  template:
    metadata:
      labels:
        name: coworking-space
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: coworking-space-service
        image: 431054597332.dkr.ecr.us-east-1.amazonaws.com/coworking-app:0.0.3
        ports:
        - containerPort: 5153
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
